### ISSUE TITLE
Open keyboard under the textfield

### ISSUE THREAD

**Issue by dferrandizmont** [ngx-material-keyboard/core#60]
Is there any way to achieve this? I'd love to pop the keyboard under the textfield as soon as I enter it and not at the bottom of the screen. 

Thanks in advance.

**Comment by davidenke** [comment]
It's not that trivial. But you could instantiate a new keyboard component like the keyboard service does and place it inside a popup using the @angular/cdk (https://material.angular.io/cdk/overlay/overview). That's the simple part. The more advanced task is to place the keyboard correctly if it extends the boundaries of the viewport or the related host element.
Don't get me wrong, but it is easier to show up the keyboard at the bottom and to ensure in the layout, that you have enough space to the bottom. But placing a keyboard inside a popup below an input that is to close to the boundaries needs you to ensure there's enough space too. Or you have to place it in the opposite direction, which is more complex since you have to check to the relative parent(s)...

**Comment by davidenke** [comment]
Related to #13, #23,
